
<%@ page language="java" contentType="text/html; charset=UTF-8"
pageEncoding="UTF-8"%>

<h1>Kanlı Pazardan Ekim Devrimine; Rusya</h1>

<h2>--KANLI PAZAR</h2>
<p>Rus Hükümeti işçilerin memnuniyetsizliklerini gidermek amacı ile polis gözetiminde ve sınırlı sayı da faaliyetleri yapması şartıyla işçi sendikaların(1) oluşumuna izin vermişti.Bu izin doğrultusunda Papaz Gağon tarafından Rus Fabrika İşçileri Meclisi kuruldu. İşçi hakları konusunda devletin daha etkili adımlar atması için 1905 yılı 9 Ocak Pazar günü bir gösteri düzenlendi. İşçiler dini semboller ve Nikolay portreleri taşıyarak Kış Sarayına doğru yürüyüş düzenledi. Kış Sarayında işçiler, işçi haklarının düzenlenmesi için Çar Nikolay'a bir dilekçe verme emelindeydiler. Devlet önce bu gösteriyi kabul edeceğini söylesede o gün Kış Sarayı önünde halkı bekleyen Çar Nikolay değil, askerler ve polislerdi. Gösteri yapan halkın üzerine ateş açıldı. Bu gün Kanlı Pazar olarak tarihe geçti. Kanlı Pazar üzerine halk daha da isyan etmeye başladı. Hükümetin tonlarca teklifine rağmen bahar ve yaz aylarında sürekli olarak ülke içinde isyanlar baş gösterdi. Savaş sahasında işçiler ve polisler vardı. Yukarı seyircilerde ise işçileri o örgütlemese de destekleyen Lenin, polis ve askerleri de işçiler ile savaşa zorlayan Çar II. Nikolay vardı. 
Yüksek kayıp veren halk 1906 yılında daha fazla savaşamadı. Hükümet kontrolu tekrardan ele geçirmişti.<br>


<h2>--1. DÜNYA SAVAŞI VE 1917 YILI</h2>

Rusya'nın 1. Dünya Savaşına katılışı ile halkta tekrardan bir huzursuzluk oluşuyordu. Oluşan bu huzursuzluk 1905 yılından daha etkili sebep olacağı bilinse de ne hükümet ne de Çar bu durum için bir çözüm arıyordu. Bu huzursuzluk tekrardan grevlerin başlamasına sebebiyet verdi. Grevleri protestolar takip etmeye başladı. Tekrardan halk polis ile çatışacak duruma gelmişti. Şubat ayının sonlarında artık çoğu askerde bu durumdan bıkmıştı. İsyancı halkın safına geçen askerler ortaya çıkmıştı ve bu olay hükümeti git gide yok ediyordu. Tüm bunlar Dünyayı etkileyecek büyük bir devrime, 1917 devrimine sebebiyet verdi. 
1917 Devriminin temel sebepleri Kanlı Pazar'ın başlayış sebepleri ile aynıdır. Aralarında ki en büyük fark ise 1. Dünya Savaşı ve Bolşevik partisinin etkisi. Askerlerin saf değiştirmesi hükümeti silahsız duruma getirmiştir. Bolşevik Partisi de hükümete karşı oluşmuş işçinin yanında olan Lenin önderliğinde ki büyük bir partidir. Hükümetin elinde Lenin, Stalin, Troçki gibi kalitli adamların bulunmayışı da hükümeti ayrı bir güçsüz kılıyordu. Tüm bu harmanlamalar ile 1907 Şubat ayında Çarlık Hükümetine karşı bir devrim gerçekleştirildi.
Devrimin bir sebebi de Duma olaylarıdır. İçişleri bakanı Peter Stoplin Duma da ki seçimlerde halkın oy etkisinin çok az etkisi olacak şekilde yoğunlukla seçim hakkının soylulara, zenginlere aktarılmasını sağladı. Halk Duma dan ümit umsa da Duma halk için hiçbir yarar sağlamayacak hale gelmişti. Duma Çar'a karşı fikirler barındırdığı için Çar tarafından lağvedildi.
Şubat ayının sonlarına doğru silahlanmış halk ile isyancı askerler devlet binalarının çoğunu ele geçirmişti. Bakanların bulunduğu Marinski Sarayının ele geçirilişinden sonra Çar II. Nikolay durumun ciddiyetini anlayarak Petrograd'tan kaçmıştır. Silahlı halkın başkenti ele geçirmesiyle devrim gerçekleşmişti. Devrimin gerçekleşişi ile burjuva sınıf tarafından bir geçici hükümet kuruldu. Bu hükümetin başına Prens Lvov getirilmişti.
Empreryalist devletlerin planınca çar 2. Nikolay tahttan burjuvalar aracılığı ile indirilip başa kardeşini getirmekti. Burjuvalar gerekli isyanı yapamadan halk işe el atmıştı. Bu yüzden emperyalizmin düşlediği gibi bir durum açığa çıkmamıştır. Gene de emperyalizm durumu toparlamak için çar Nikolay tahttan indiğinde burjuvalar kardeşi Knez Mihail Aleksandroviç'e teklif sunacaklardı. Mihail'in teklifi reddetmesi ile 1613 de başlayan hanedanlk 1917 de bitecekti.
<br>
23 Şubatı tetikleyen etken Petrograd Sosyal Demokratları'nın yayınladığı hükümeti suçlu gösteren bildiridir. BU bildiri ile halk ayaklanıp protestolara başlamıştır. Bu ayaklanma vesilesiyle 2 Mart 1917 de çar tahttab feragat etmiştir. 3 Mart 1917 tarhinde ise kimse farketmese de bin yıllık monarşi, dört yüz yıllık çarlık ve üç yüz yıllık Romanov Hanedanlığı son ermişti.
<br>
3 Temmuz 1917 tarihinde 1. Makineli tüfek alayının askerleri Geçici Hükümet aleyhinde bir gösteri düzenlemeye karar verdiler. Askerler halka da haberler salarak büyük bir birlik oluşturdu. Bu büyük birlik 500 bin kişiye kadar ulaşmıştır, Lenin bu koca kalabalığın yönetimini üstlenmişti. 4 Temmuz Sabahı 500 bin kişiye iktidarın Sovyetlere verilmesi gerektiğini anlatan bir konuşma yaptı. Bu Temmuz krizinden sonra hükümet başına Kerenski getirildi. Kerenski kendi intihar emrini "cephelerde taaruz emri vererek" vermiştir. Temmuz olaylarından sonra hükümet Lenin'i alman ajanlığı ile suçlayacaktı bu yüzden Lenin tekrardan saklanarak yaşayacaktı. Peki Lenin hakikaten Alman ajanı mıydı? Elbette hayır Almanlardan destek almıştır fakat bu ajanlığındann dolayı değildir, Almanlarında Lenin'in de istedikleri şey çarlık Rusyasının devrilmesiydi. Aralarında böyle bir ortak çıkar haricinde başka birşey yoktur(Şimdiki bildiklerime göre yoktur)
Gerek ekonomik ve sosyal krizlerin devamı gerekte savaşın devamı Geçici hükümeti halkın ve askerlerin gözünden iyice düşürmüştü. Bu kriz ortamı sonucunda 1917 Ekim ayında Bolşevikler yönetimi ele geçirmişlerdir.
<br>
<h2>Kurucu Meclis</h2>
Halk artık diğer tüm reformlardan sonra siyasi bir reform istemekteydi. Demokratik bir kurucu meclis halkın isteğiyi ve bundan umutluydular. 1918 karmaşasında planlanan Kurucu Meclis gelecek için bir umut ışığı olmuştu. Geçici hükümet kurucu meclis için seçimleri organize etmeyi istiyordu. Fakat bunu yapabilmeleri için çok fazla eksik vardı. 25 Mayıs 1017 de kurucu meclis seçimleri için ilk özel komisyon toplantısı yapılmıştı. Bu toplantıda yalnız ruslar değil, yabancı uyruklu rusya da yaşayan vekillerde katılacaktı. Başkan Lvov hükümetinin düşmesi ve başa Kerneski'nin geçişi ile bu komisyonda unutuldu. 27 Ekim 1917 de bolşeviklerin yönetimi ele geçirişi ile kurucu meclis seçimleri 12 Kasım'a çekildi. Seçimler sonucu Sosyal Devrimciler partisi bolşeviklerden daha üsttelerdi. Bolşevikler bunun üzerine Sosyal Devrimciler üzerine iftiralar atıp partinin dağıldığını iddia etti. Kurucu Meclisi Lenin temsili ve çarpık olmakla suçladı. Her duruma karşı bolşevikler ordularını hazırda tutuyorlardı. Günün birinde meclis kapısında kızıl ordu askerleri bekliyordu ve meclise kimseyi almıyorlardı. Lenin şöyle dedi;
Tüm kuvvet ve hakları ele geçirdik ve Kurucu Meclis sosyalist bir devlette işlevisz olacaktır. Kurucu meclis burjuva topluluğuna ait siyasi ideallerin en büyük aracıdır.
Rusyanın demokratik bir hükümete geçme adına yaptığı ilk gerçek girişim tarihe karışmıştı ve bununla birlikte bolşevik dikdatörlüğü yükselmiştir.
<br>
<h2>Ekim Devrimi</h2>
<p>25 Ekim 1917 yılında Petrograd Kış sarayı hariç halk ile doluydu. Lenin'in Finlandiya'dan gelişiyle bu sefer daha büyük bir isyan vardı. kongre de Bolşevikler başa geçmek için çabalıyordu. Rakipleri sağ Sosyal Devrimciler ve Menşeviklerin alınan kararlar sonucu Kongreyi terk etmeleriyle Bolşeviklere karştı bir parti kalmamıştı. 
26 Ekim 1917 de Bolşevikler Geçici Hükümet'in görevlerini yürüttüğü Kış Sarayını da ele geçirmesiyle hükümet Bolşeviklerin eline geçmiştir.
<br>
1-->Sendika, çalışanların sosyal, ekonomik hak ve çıkarlarını korumak, sorunlarını çözme amacı ile kurulmuş ekonomik öğeler taşıyan, devlet, siyasi parti ve iktidar örgütlenmelerinden bağımsız örgütlerdir.
</p>